# Generated by Django 2.0.5 on 2018-06-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qsuestion_text',
            new_name='question_text',
        ),
    ]
